---
- name: Add gitlab runner package repository
  become: yes
  ansible.builtin.get_url:
    url: "https://packages.gitlab.com/install/repositories/runner/gitlab-runner/script.deb.sh"
    owner: nobody
    group: nogroup
    mode: 0644
    register: gitlab_runner_script

- name: Run the script
  become: yes
  ansible.builtin.command:
    /script.deb.sh
  when: gitlab_runner_script

- name: Install the latest gitlab runner
  become: yes
  ansible.builtin.command:
    export GITLAB_RUNNER_DISABLE_SKEL=true; sudo -E apt-get install gitlab-runner
  when: gitlab_runner_script
